[platformio]
default_envs = m5stack-tab5

[env:m5stack-tab5]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = esp32-p4-evboard
framework = arduino
extra_scripts =
  pre:add_framework_includes.py
  pre:esp_tts_integration.py
board_build.partitions = partitions.csv
board_build.mcu = esp32p4
board_build.flash_mode = qio
monitor_speed = 115200
upload_speed = 1500000
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=5
  -DCODEX_DESK_FIRMWARE_VERSION=\"0.1.0\"
lib_ldf_mode = deep+
lib_deps =
  WiFi
  Network
  NetworkClientSecure
  https://github.com/M5Stack/M5Unified.git
  https://github.com/M5Stack/M5GFX.git
  bblanchon/ArduinoJson@7.4.3
  links2004/WebSockets@2.7.2
